# -*- coding: utf-8 -*-
"""Shared offset calibration timing configuration."""

OFFSET_COLLECTION_SECONDS = 5.0
OFFSET_STABLE_WINDOW_SECONDS = 3.0
OFFSET_COLLECTION_COMMAND_SECONDS = int(OFFSET_COLLECTION_SECONDS)
OFFSET_PROCESS_GRACE_SECONDS = 0.5
OFFSET_MAX_PROCESS_SECONDS = OFFSET_COLLECTION_SECONDS + OFFSET_PROCESS_GRACE_SECONDS
OFFSET_PROGRESS_SECONDS = OFFSET_MAX_PROCESS_SECONDS
OFFSET_STOP_GUARD_DELAY_MS = int(OFFSET_MAX_PROCESS_SECONDS * 1000)
